In [1]:
import cv2 
import numpy as np 
import matplotlib.pyplot as plt
plt.rcParams['figure.figsize'] = [10, 3]

def display_img(img):
    new_img= cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    plt.imshow(new_img)
    plt.show()

# Task 1

In [2]:
#loading video
vid1 = cv2.VideoCapture('./Task2-assets/videocut.mp4') 
#function to mask and extract color from each frame
def maskframe(vid1):
    _, frame = vid1.read()
    mod_frame = frame 
    hsv_image = cv2.cvtColor(mod_frame, cv2.COLOR_BGR2HSV)
    # extract blue
    hsv_lower = np.array([94, 35, 176])
    hsv_upper = np.array([113, 210, 255])
    extracted_image = cv2.inRange(hsv_image, hsv_lower, hsv_upper)  
    
    _, frame = vid1.read()
    mod_frame = frame
    hsv_image = cv2.cvtColor(mod_frame, cv2.COLOR_BGR2HSV)
    # extract blue
    hsv_lower = np.array([94, 35, 176])
    hsv_upper = np.array([113, 210, 255])
    extracted_image = cv2.inRange(hsv_image, hsv_lower, hsv_upper)
    
    masked_image= cv2.bitwise_and(mod_frame, mod_frame, mask=extracted_image)
    return masked_image

In [12]:
#displaying modified frames in loop
while(1):
  imgFrame = maskframe(vid1)
  cv2.imshow('Modified video', imgFrame)
  if imgFrame is None: 
      break
  if cv2.waitKey(20) & 0xFF == ord('q'):
      break

vid1.release()
cv2.destroyAllWindows()

# Task 2 

# Task 3

In [ ]:
newimg = None

img=cv2.imread('./Task2-assets/color.jpg') 
mod_img=cv2.cvtColor(img,cv2.COLOR_BGR2HSV)

def changeToPxColor(event,x,y,flags,param):
    global newimg
    if event == cv2.EVENT_LBUTTONDOWN:
            h = mod_img[y, x, 0]
            v= mod_img[y, x, 1]
            s = mod_img[y, x, 2] 
            print(h, v, s)
        
            #extracting the color
            hsv_low = np.array([h-10, s-80, v-70])
            hsv_high = np.array([h+10, s+80, v+70])
            extracted_image = cv2.inRange(mod_img,hsv_low ,hsv_high )

            #extracting the color
            hsv_low = np.array([h-10, s-80, v-70])
            hsv_high = np.array([h+10, s+80, v+70])
            print(hsv_high)
            extracted_image = cv2.inRange(mod_img, hsv_low, hsv_high)
            newimg= cv2.bitwise_and(img, img, mask=extracted_image)
            #newimg = cv2.cvtColor(newimg,cv2.COLOR_BGR2HSV)

cv2.namedWindow('colors')
cv2.setMouseCallback('colors',changeToPxColor)

while(1):
    cv2.imshow('colors',img)
    if newimg is not None:
        cv2.imshow('new color', newimg)
    key = cv2.waitKey(1)
    if key == 27:
        break
cv2.destroyAllWindows()


122 254 213
[132 293 324]
149 253 162
[159 242 323]
148 253 235
[158 315 323]
11 252 230
[ 21 310 322]
1 252 225
[ 11 305 322]
149 252 147
[159 227 322]
121 252 95
[131 175 322]
122 255 157
[132 237 325]
121 251 244
[131 324 321]
99 255 150
[109 230 325]
99 253 240
[109 320 323]
120 10 209
[130 289  80]
120 7 255
[130 335  77]
120 9 225
[130 305  79]
120 9 225
[130 305  79]
120 10 197
[130 277  80]
26 255 221
[ 36 301 325]
65 253 168
[ 75 248 323]
65 251 136
[ 75 216 321]
66 255 205
[ 76 285 325]
1 253 132
[ 11 212 323]
2 255 230
[ 12 310 325]
10 255 243
[ 20 323 325]
148 255 255
[158 335 325]
121 251 244
[131 324 321]
120 9 228
[130 308  79]
125 10 153
[135 233  80]
126 10 125
[136 205  80]
115 9 173
[125 253  79]
120 7 69
[130 149  77]
120 5 97
[130 177  75]
120 8 62
[130 142  78]
120 64 8
[130  88 134]
30 26 20
[ 40 100  96]
0 0 13
[10 93 70]
0 0 47
[ 10 127  70]
30 20 25
[ 40 105  90]
0 0 11
[10 91 70]
120 8 61
[130 141  78]
11 251 193
[ 21 273 321]
149 253 128
[159 208 323]
148 25